"""Concept generator v1 on the fictional pilot plot: search per parti, critique, write specs and a report.

    python scripts/concept.py generate [-n 1500]     # writes spec/concepts/pilot/ and docs/guidance/concepts-pilot.md
    python scripts/concept.py calibrate              # the critic on room-graph precedents and seeded mutations

Every concept is DIAGNOSTIC: the geometric checks have no published
dimensioned precedent to calibrate against yet (ADR-0016). Never shown to a
client as a design.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from archpipe.concept import critic, generator as G, layout as L

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "spec" / "concepts" / "pilot"
DOC = ROOT / "docs" / "guidance" / "concepts-pilot.md"
IMG = ROOT / "docs" / "guidance" / "concepts-pilot"


def draw(layout, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Rectangle
    lv = sorted(layout["levels"], key=layout["levels"].get)
    fig, axes = plt.subplots(1, len(lv), figsize=(6 * len(lv), 7.5))
    W, D = layout["plot"]["width_m"], layout["plot"]["depth_m"]
    for ax, lid in zip(axes, lv):
        ax.add_patch(Rectangle((0, 0), W, D, fill=False, ls="--", lw=0.8, ec="0.5"))
        for rid, r in layout["rooms"].items():
            if r["level"] != lid:
                continue
            x0, y0, x1, y1 = r["rect"]
            circ = r["occupancy"] in ("corridor", "landing", "stair", "entrance")
            ax.add_patch(Rectangle((x0, y0), x1 - x0, y1 - y0, fc="0.93" if circ else "white", ec="k", lw=1.2))
            ax.text((x0 + x1) / 2, (y0 + y1) / 2, f"{rid}\n{(x1 - x0) * (y1 - y0):.0f} m²", ha="center", va="center",
                    fontsize=6.5)
        doors, wins, _ = L.openings(layout, lid)
        for w in wins:
            (a, b), (c, d) = w["segment"][0], w["segment"][1]
            mx, my = (a + c) / 2, (b + d) / 2
            h = w["width"] / 2
            ax.plot([mx - h, mx + h] if b == d else [mx, mx], [my, my] if b == d else [my - h, my + h], c="tab:blue", lw=3)
        for dr in doors:
            (a, b), (c, d) = dr["segment"][0], dr["segment"][1]
            ax.plot((a + c) / 2, (b + d) / 2, "o", ms=3.5, c="tab:red" if None in dr["rooms"] else "tab:orange")
        ax.set_xlim(-1, W + 1)
        ax.set_ylim(-1, D + 1)
        ax.set_aspect("equal")
        ax.set_title(f"{layout['id']}  {lid}  (N up; road south)", fontsize=9)
        ax.tick_params(labelsize=6)
    fig.suptitle("GENERATED CONCEPT - DIAGNOSTIC, NOT A DESIGN. blue = window, orange = door, red = entrance",
                 fontsize=8)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=110)
    plt.close(fig)


def generate(n):
    rows = []
    for parti in G.PARTIS:
        lay, res, tried = G.search(parti, n)
        OUT.mkdir(parents=True, exist_ok=True)
        (OUT / f"{parti}.layout.json").write_text(json.dumps(lay, indent=1) + "\n", encoding="utf-8")
        spec = L.write_spec(lay, OUT / f"{parti}.yaml")
        findings = critic.rule_findings(spec)
        draw(lay, IMG / f"{parti}.png")
        rows.append((parti, lay, res, tried, findings))
    lines = ["# Pilot concepts: generator v1 (DIAGNOSTIC)", "",
             "Generated by `python scripts/concept.py generate` on the fictional pilot "
             "(`knowledge/projects/villa-pilot.json`: 30 x 40 m plot, road south, garden north, "
             "272 m2 programme, 400 m2 scenario allowance). The real villa (Sheikh Zayed) is untouched.", "",
             "**Status: diagnostic.** The critic's graph checks are calibrated against published room graphs "
             "(tests/test_concept_calibration.py). Its geometric checks are not: no held book gives a labelled, "
             "dimensioned house plan to calibrate them against. So these are not concepts to show a client; they "
             "show that the search-and-critique chain runs end to end.", "",
             "Generator settings (not standards): corridor 1.3 m, stair allowance 2.6 m run, minimum room run 1.8 m, "
             "building 6 m from the road boundary (setbacks not supplied), storey 3.3 m.", ""]
    for parti, lay, res, tried, findings in rows:
        lines += [f"## {parti}: `{lay['id']}` (best of {tried} variants)", "",
                  f"![{parti}](concepts-pilot/{parti}.png)", "",
                  f"Spec: `spec/concepts/pilot/{parti}.yaml` (loads with `archpipe.model.load`).", "",
                  "| Check | Status | Detail |", "|---|---|---|"]
        for c in res["checks"]:
            detail = {k: v for k, v in c.items() if k not in ("check", "status", "basis")}
            lines.append(f"| {c['check']} | {c['status']} | `{json.dumps(detail)[:180]}` |")
        by = {}
        for f in findings:
            by.setdefault((f["rule"], f["severity"]), []).append(f["where"])
        lines += ["", "Rule engine on the emitted spec (legacy rules are diagnostic per the rule audit): " +
                  ("; ".join(f"{r} {s} x{len(w)}" for (r, s), w in sorted(by.items())) or "no findings"), ""]
    lines += ["## Check bases", ""] + [f"- **{k}**: {v}" for k, v in critic.BASIS.items()] + [
        "", "## Not assessed (consultant scope or not yet run)", "",
        "- Cooling per concept: run the thermal shoebox per facade (`workstation.py thermal`) before choosing.",
        "- Structure, glare, HVAC, electrical, plumbing: MISSING in-house; consultant hand-off.", ""]
    DOC.write_text("\n".join(lines), encoding="utf-8")
    for parti, lay, res, _, findings in rows:
        print(f"  {parti:4s} {lay['id']:10s} fails={res['fails']} rule findings={len(findings)}")
    print(f"  report: {DOC.relative_to(ROOT)}")
    return 0


def calibrate():
    import unittest
    suite = unittest.defaultTestLoader.loadTestsFromName("tests.test_concept_calibration")
    return 0 if unittest.TextTestRunner(verbosity=2).run(suite).wasSuccessful() else 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("cmd", choices=["generate", "calibrate"])
    ap.add_argument("-n", type=int, default=1500)
    a = ap.parse_args(argv)
    return generate(a.n) if a.cmd == "generate" else calibrate()


if __name__ == "__main__":
    sys.exit(main())
