"""Pick a real product, install it in a copy of the bedroom, and test it end to end.

    python scripts/luminaire_demo.py --replace LT-01 --product signify 911401840687 0 \
        --mounting-height 2700 --require '{"kelvin": 3000, "cri_min": 80, "lumens": [2500, 4500]}' --tag a

Writes a generated demo spec under out/demo/<tag>/ -- the approved bedroom
spec is never edited -- then runs the same chain as the bedroom: spec ->
Revit build -> extract -> round-trip check (emitter measured from the
manufacturer's geometry) -> render input -> lux report -> the product
against the design's requirement. Run again with another product and
--tag b to swap; out/demo/compare.json sets the runs side by side.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from archpipe import photometry as ph                              # noqa: E402
from archpipe.luminaires.install import expectations, load_spec    # noqa: E402

DERIVED = ("lumens", "watts", "kelvin", "cri", "ies", "family")


def run(argv, env, timeout, log):
    res = subprocess.run([str(a) for a in argv], cwd=ROOT, env=env, stdin=subprocess.DEVNULL,
                         capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=timeout)
    log.write_text(res.stdout + res.stderr, encoding="utf-8")
    return res


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--base", type=Path, default=ROOT / "spec/bedroom-test.yaml")
    ap.add_argument("--replace", required=True, help="spec lighting id to replace")
    ap.add_argument("--product", nargs=3, metavar=("MANUFACTURER", "SKU", "LAMP_SET"), required=True)
    ap.add_argument("--mounting-height", type=float, required=True, help="emitter height, mm")
    ap.add_argument("--require", default="{}", help="design requirement JSON")
    ap.add_argument("--tag", default="a")
    ap.add_argument("--skip-revit", action="store_true")
    a = ap.parse_args(argv)

    out = ROOT / "out/demo" / a.tag
    out.mkdir(parents=True, exist_ok=True)
    spec = yaml.safe_load(a.base.read_text(encoding="utf-8"))
    old = next(l for l in spec["lighting"] if l["id"] == a.replace)
    new = {k: v for k, v in old.items() if k not in DERIVED}
    new.update(mounting_height=a.mounting_height,
               product={"manufacturer": a.product[0], "sku": a.product[1], "lamp_set": int(a.product[2])},
               requirement=json.loads(a.require))
    spec["lighting"] = [new if l["id"] == a.replace else l for l in spec["lighting"]]
    spec["name"] = spec.get("name")
    demo_spec = out / "spec.yaml"
    demo_spec.write_text("# GENERATED by scripts/luminaire_demo.py from %s -- not an approved design\n"
                         % a.base.relative_to(ROOT) + yaml.safe_dump(spec, sort_keys=False), encoding="utf-8")

    env = {**os.environ, "PYTHONIOENCODING": "utf-8", "PYTHONPATH": str(ROOT / "src"),
           "ARCHPIPE_SPEC": str(out / "spec.json"), "ARCHPIPE_FAMILY_DIR": str(ROOT / "out/families"),
           "ARCHPIPE_IES_DIR": r"C:\ProgramData\Autodesk\RVT 2027\IES",
           "ARCHPIPE_PRODUCT_IES_DIR": str(ph.PRODUCT_IES_DIR),
           "ARCHPIPE_BEDROOM_OUT": str(out / "model.rvt"), "ARCHPIPE_BUILD_REPORT": str(out / "build.json"),
           "ARCHPIPE_MODEL": str(out / "model.rvt"), "ARCHPIPE_EXTRACT_OUT": str(out / "extract.json")}
    steps = {}
    r = run([sys.executable, ROOT / "scripts/make_bedroom_spec.py", "--spec", demo_spec, "--out", out / "spec.json"],
            env, 120, out / "spec.log")
    steps["spec"] = r.returncode
    if r.returncode:
        print((out / "spec.log").read_text(encoding="utf-8"))
        return 1
    if not a.skip_revit:
        pr = Path(os.environ["APPDATA"]) / "pyRevit-Master/bin/pyrevit.exe"
        for script, timeout in (("build_bedroom.py", 900), ("extract_model.py", 600)):
            try:
                r = run([pr, "run", ROOT / "revit" / script, "--revit=2027"], env, timeout, out / (script[:-3] + ".log"))
                steps[script] = r.returncode
            except subprocess.TimeoutExpired:
                steps[script] = "timeout (a modal dialog? see revit/unattended.py)"
                print(f"{script}: timed out after {timeout}s")
                return 1
        build = json.loads((out / "build.json").read_text())
        steps["revit_messages"] = build.get("revit_messages")
        steps["build_errors"] = build.get("errors")
        steps["light"] = [l for l in build["lighting"] if l["id"] == a.replace]
    r = run([sys.executable, ROOT / "scripts/check_bedroom.py", "--spec", demo_spec, "--extract", out / "extract.json"],
            env, 120, out / "check.log")
    steps["roundtrip"] = r.returncode
    r = run([sys.executable, ROOT / "scripts/make_render_input.py", "--extract", out / "extract.json", "--spec", demo_spec,
             "--ies-dir", "assets/ies", "--out", out / "render.json"], env, 120, out / "render_input.log")
    steps["render_input"] = r.returncode
    r = run([sys.executable, ROOT / "scripts/lighting_report.py", out / "render.json", "--json", out / "lighting.json",
             "--out-svg", out / "lux.svg"], env, 300, out / "lighting.log")
    steps["lighting"] = r.returncode
    item = next(l for l in load_spec(demo_spec)["lighting"] if l["id"] == a.replace)
    exp = expectations(item)
    lux = json.loads((out / "lighting.json").read_text()) if (out / "lighting.json").is_file() else {}
    summary = {"tag": a.tag, "replaced": a.replace, "product": item["product"], "derived": {k: item.get(k) for k in DERIVED},
               "requirement": item.get("requirement"),
               "expectations": [{"check": n, "passed": ok, "detail": d} for n, ok, d in exp],
               "roundtrip_lines": [l for l in (out / "check.log").read_text(encoding="utf-8").splitlines()
                                   if a.replace in l or "checks," in l],
               "lux": {"average": lux.get("average_lx"), "max": lux.get("maximum_lx"),
                       "task_points": {t["label"]: t["lux"] for t in lux.get("task_points", [])},
                       "verdicts": lux.get("verdicts")},
               "steps": steps}
    (out / "summary.json").write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")
    runs = {}
    for f in sorted((ROOT / "out/demo").glob("*/summary.json")):
        s = json.loads(f.read_text())
        runs[s["tag"]] = {"product": f"{s['product']['manufacturer']}/{s['product']['sku']} ls{s['product']['lamp_set']}",
                          "luminaire_lm": s["product"]["luminaire_lm"], "kelvin": s["derived"]["kelvin"],
                          "expectations_passed": all(e["passed"] for e in s["expectations"]),
                          "lux": s["lux"]}
    (ROOT / "out/demo/compare.json").write_text(json.dumps(runs, indent=2), encoding="utf-8")
    print(json.dumps({k: summary[k] for k in ("product", "expectations", "roundtrip_lines", "lux", "steps")},
                     indent=2, default=str))
    ok = (steps.get("roundtrip") == 0 and steps.get("lighting") in (0, 1)
          and all(e["passed"] for e in summary["expectations"]))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
