"""Generate Claude/Codex adapters from shared skill sources and role records."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    outputs = {}
    for path in (ROOT/'.agents/skills').glob('*/SKILL.md'):
        outputs[ROOT/'.claude/skills'/path.parent.name/'SKILL.md'] = path.read_text(encoding='utf-8')
    for role in json.loads((ROOT/'agents/roles.json').read_text()):
        name, desc, instruction = role['name'], role['description'], role['instructions']
        outputs[ROOT/'.codex/agents'/(name+'.toml')] = (
            '# Generated by scripts/sync_agent_assets.py\n'
            f'name = {json.dumps(name)}\ndescription = {json.dumps(desc)}\n'
            f'developer_instructions = {json.dumps(instruction)}\n')
        outputs[ROOT/'.claude/agents'/(name+'.md')] = (
            f'---\nname: {name}\ndescription: {json.dumps(desc)}\n---\n\n'
            '<!-- Generated by scripts/sync_agent_assets.py -->\n'+instruction+'\n')
    stale = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text(encoding='utf-8') != content:
            stale.append(str(path.relative_to(ROOT)))
            if not a.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding='utf-8')
    if a.check and stale:
        print('STALE adapters:', ', '.join(stale))
        return 1
    print(('Checked' if a.check else 'Generated'), len(outputs), 'agent/skill adapters')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
